// MEASUREMENTs
export const LOAD_MEASUREMENTS_REQUEST = 'LOAD_MEASUREMENTS_REQUEST'
export const LOAD_MEASUREMENTS_SUCCESS = 'LOAD_MEASUREMENTS_SUCCESS'
export const LOAD_MEASUREMENTS_FAILURE = 'LOAD_MEASUREMENTS_FAILURE'

// Single MEASUREMENT
export const LOAD_MEASUREMENT_REQUEST = 'LOAD_MEASUREMENT_REQUEST'
export const LOAD_MEASUREMENT_SUCCESS = 'LOAD_MEASUREMENT_SUCCESS'
export const LOAD_MEASUREMENT_FAILURE = 'LOAD_MEASUREMENT_FAILURE'
